package com.github.myrrhax.diploma_project.command.index;

import com.github.myrrhax.diploma_project.command.MetadataCommand;
import com.github.myrrhax.diploma_project.command.SchemaDifference;
import com.github.myrrhax.diploma_project.model.ColumnMetadata;
import com.github.myrrhax.diploma_project.model.IndexMetadata;
import com.github.myrrhax.diploma_project.model.SchemaStateMetadata;
import com.github.myrrhax.diploma_project.model.TableMetadata;
import com.github.myrrhax.diploma_project.model.exception.ApplicationException;
import com.github.myrrhax.diploma_project.util.MetadataTypeUtils;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

import java.util.Arrays;
import java.util.UUID;

@Getter
@Setter
public class AddIndexCommand extends MetadataCommand {
    @NotNull
    private UUID tableId;
    @NotNull
    @NotEmpty
    private UUID[] affectedColumns;
    private String indexName;
    private boolean unique = false;
    @NotNull
    private IndexMetadata.IndexType indexType = IndexMetadata.IndexType.B_TREE;

    @Override
    public SchemaDifference execute(SchemaStateMetadata metadata) {
        TableMetadata table = metadata.getTable(tableId).orElseThrow(() ->
                new ApplicationException("error.table.notfound"));

        IndexMetadata builtIndex = IndexMetadata.builder()
                .indexType(indexType)
                .columnIds(Arrays.asList(affectedColumns))
                .unique(unique)
                .table(table)
                .tableId(tableId)
                .schemaState(metadata)
                .build();
        if (indexName != null
            && !indexName.isBlank()) {
            if (table.containsIndex(indexName)) {
                throw new ApplicationException("");
            }

            builtIndex.setName(indexName);
            builtIndex.setNameAutogenerated(false);
        } else {
            builtIndex.computeAndSetName();
        }

        if (unique && affectedColumns.length == 1) {
            ColumnMetadata column = table.getColumn(affectedColumns[0])
                    .orElseThrow(() -> new ApplicationException("error.column.notfound"));
            if (column.getConstraints().contains(ColumnMetadata.ConstraintType.UNIQUE)) {
                throw new ApplicationException("error.indexes.index-already-exists");
            }
        }

        if (table.getIndexes().values()
                .stream().anyMatch(builtIndex::equals)
            || MetadataTypeUtils.isFullEquals(table.getPrimaryKeyParts(), builtIndex.getColumnIds())) {
            throw new ApplicationException("error.indexes.index-already-exists");
        }

        table.addIndexes(builtIndex);
        SchemaDifference diff = new SchemaDifference();
        diff.upsertIndex(builtIndex);

        return diff;
    }
}
