services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - docker/.env
    restart: always
    networks:
      - backend
    volumes:
      - pg_db:/var/lib/postgresql

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    hostname: rabbitmq
    restart: always
    env_file:
      - docker/.env
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  core:
    container_name: core
    build:
      context: .
      dockerfile: core/Dockerfile
      args:
        - PORT=8000
    restart: unless-stopped
    env_file:
      - docker/.env
    environment:
      - SERVER_PORT=8000
    depends_on:
      - db
      - rabbitmq
      - redis
    networks:
      - backend

  notifications:
    container_name: notifications
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    restart: unless-stopped
    env_file:
      - docker/.env
    depends_on:
      - rabbitmq
    networks:
      - backend

  redis:
    image: redis:7.2-alpine
    container_name: redis_cache
    volumes:
      - redis_data:/data

networks:
  backend:
    driver: bridge

volumes:
  pg_db:
  rabbitmq:
  redis_data: