package com.github.myrrhax.diploma_project.script;

import com.github.myrrhax.diploma_project.model.ColumnMetadata;
import com.github.myrrhax.diploma_project.model.ReferenceMetadata;
import com.github.myrrhax.diploma_project.model.TableMetadata;
import com.github.myrrhax.diploma_project.model.exception.ApplicationException;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.UUID;

public abstract class AbstractSqlScriptBuilder extends AbstractScriptBuilder {
    protected static final String FK_TEMPLATE =
            """
            ALTER TABLE %s
            ADD CONSTRAINT %s
            FOREIGN KEY (%s)
            REFERENCES %s (%s)
            ON DELETE %s
            ON UPDATE %s;
            
            """;

    @Override
    public void appendHeader(StringBuilder sqlBuilder, String name) {
        sqlBuilder.append("/*\n\tGenerated by ErmDev. Version tag: ")
                .append(name)
                .append("\n*/\n");
    }

    @Override
    public void appendReferenceDefinition(StringBuilder sqlBuilder,
                                          String refName,
                                          TableMetadata baseTable,
                                          TableMetadata referencedTable,
                                          String[] baseColumnNames,
                                          String[] referencedColumnNames,
                                          ReferenceMetadata.OnDeleteAction onDeleteAction,
                                          ReferenceMetadata.OnUpdateAction onUpdateAction) {
        sqlBuilder.append(String.format(
                FK_TEMPLATE,
                baseTable.getName(),
                refName,
                String.join(", ", baseColumnNames),
                referencedTable.getName(),
                String.join(", ", referencedColumnNames),
                parseAction(onDeleteAction),
                parseAction(onUpdateAction)
        ));
    }

    @Override
    public void appendTableDefinition(StringBuilder sqlBuilder, TableMetadata tableMeta) {
        sqlBuilder.append("CREATE TABLE IF NOT EXISTS ")
                .append(tableMeta.getName())
                .append("(\n");
    }

    @Override
    protected void appendEndTablePart(StringBuilder scriptBuilder) {
        scriptBuilder.append(");\n\n");
    }

    @Override
    public void appendColumnDefinition(StringBuilder sqlBuilder, ColumnMetadata column, boolean addExisting) {
        String typeName = getSuitableType(column);
        if (!addExisting) {
            sqlBuilder.append('\t');
        }
        sqlBuilder.append(column.getName())
                .append(" ")
                .append(typeName);
        List<ColumnMetadata.ConstraintType> constraints = column.getConstraints();

        if (constraints.contains(ColumnMetadata.ConstraintType.NOT_NULL)) {
            sqlBuilder.append(" NOT NULL");
        }

        if (column.getDefaultValue() != null) {
            sqlBuilder.append(" DEFAULT ").append(column.getDefaultValue());
        }
        if (!addExisting) {
            sqlBuilder.append(',');
        }
    }

    @Override
    public void appendDropTable(StringBuilder scriptBuilder, TableMetadata fromTable) {
        scriptBuilder.append("DROP TABLE IF EXISTS ")
                .append(fromTable.getName())
                .append(";\n");
    }

    public void appendPrimaryKeyDefinition(StringBuilder sqlBuilder, TableMetadata table) {
        sqlBuilder.append("CONSTRAINT ")
                .append("pk_")
                .append(table.getName().toLowerCase());
        sqlBuilder.append(" PRIMARY KEY (");

        List<UUID> primaryKeyParts = new ArrayList<>(table.getPrimaryKeyParts());
        for (int i = 0; i < primaryKeyParts.size(); i++) {
            ColumnMetadata column = table.getColumn(primaryKeyParts.get(i)).orElseThrow();
            sqlBuilder.append(column.getName());
            if (i < primaryKeyParts.size() - 1) {
                sqlBuilder.append(", ");
            }
        }
        sqlBuilder.append(")\n");
    }

    protected String getMinMaxDefinition(ColumnMetadata column) {
        boolean hasMin = column.getMin() != null;
        boolean hasMax = column.getMax() != null;

        if (!hasMin && !hasMax) {
            throw new ApplicationException("Failed to generate min/max definition");
        }
        boolean hasBetween = hasMin && hasMax;
        StringBuilder result = new StringBuilder();
        result.append("CHECK(");
        result.append(column.getName());

        if (hasBetween) {
            result.append(" BETWEEN ");
            result.append(column.getMin());
            result.append(" AND ").append(column.getMax());
        } else if (hasMin) {
            result.append(" >= ").append(column.getMin());
        } else {
            result.append(" <= ").append(column.getMax());
        }

        result.append(")");
        return result.toString();
    }

    @Override
    public String getDecimalDefinition(ColumnMetadata column) {
        return "DECIMAL(" + column.getPrecision() + ", " + column.getScale() + ")";
    }

    @Override
    public void addColumnToTable(StringBuilder scriptBuilder, ColumnMetadata column) {
        TableMetadata table = column.getTable();
        scriptBuilder.append("ALTER TABLE ")
                .append(table.getName())
                .append(" ADD COLUMN ");
        appendColumnDefinition(scriptBuilder, column, true);

        if (column.getConstraints().contains(ColumnMetadata.ConstraintType.UNIQUE)) {
            scriptBuilder.append(",\nADD ");
            addUniqueConstraint(scriptBuilder, column);
        }
        if (column.getMin() != null || column.getMax() != null) {
            scriptBuilder.append(",\nADD ");
            addMinMaxConstraint(scriptBuilder, column);
        }

        if (scriptBuilder.charAt(scriptBuilder.length() - 1) == ',') {
            scriptBuilder.setCharAt((scriptBuilder.length() - 1), ';');
        } else {
            scriptBuilder.append(';');
        }
        scriptBuilder.append('\n');
    }

    @Override
    public void appendRenameColumn(StringBuilder scriptBuilder, ColumnMetadata oldColumn, ColumnMetadata newColumn) {
        scriptBuilder.append("ALTER TABLE ")
                .append(newColumn.getTable().getName())
                .append(" RENAME COLUMN ")
                .append(oldColumn.getName())
                .append(" TO ")
                .append(newColumn.getName())
                .append(";\n");
    }

    @Override
    public void appendDropColumn(StringBuilder scriptBuilder, ColumnMetadata column) {
        scriptBuilder.append("ALTER TABLE ")
                .append(column.getTable().getName())
                .append(" DROP COLUMN ")
                .append(column.getName())
                .append(";\n");
    }

    @Override
    protected void onEndTableDefinition(StringBuilder scriptBuilder, TableMetadata table) {
        List<ColumnMetadata> columns = table.getColumns().values().stream()
                .toList();

        for (ColumnMetadata column : columns) {
            if (column.getConstraints().contains(ColumnMetadata.ConstraintType.UNIQUE)) {
                scriptBuilder.append('\t');
                addUniqueConstraint(scriptBuilder, column);
                scriptBuilder.append(",\n");
            }

            if (column.getMin() != null || column.getMax() != null) {
                scriptBuilder.append('\t');
                addMinMaxConstraint(scriptBuilder, column);
                scriptBuilder.append(",\n");
            }
        }

        scriptBuilder.append('\t');
        appendPrimaryKeyDefinition(scriptBuilder, table);
    }

    protected void addMinMaxConstraint(StringBuilder scriptBuilder, ColumnMetadata column) {
        String tableName = column.getTable().getName();
        scriptBuilder.append("CONSTRAINT ")
                .append(CHECK_CONSTRAINT_PATTERN.formatted(tableName.toLowerCase(),
                        column.getName().toLowerCase()))
                .append(" ")
                .append(getMinMaxDefinition(column));
    }

    protected void addUniqueConstraint(StringBuilder scriptBuilder, ColumnMetadata column) {
        String tableName = column.getTable().getName();
        scriptBuilder.append("CONSTRAINT ")
                .append(UQ_CONSTRAINT_PATTERN.formatted(tableName.toLowerCase(),
                        column.getName().toLowerCase()))
                .append(" UNIQUE (")
                .append(column.getName())
                .append(')');;
    }

}