package com.github.myrrhax.diploma_project.script.impl.postgres;

import com.github.myrrhax.diploma_project.model.ColumnMetadata;
import com.github.myrrhax.diploma_project.model.IndexMetadata;
import com.github.myrrhax.diploma_project.model.SchemaStateMetadata;
import com.github.myrrhax.diploma_project.model.TableMetadata;
import com.github.myrrhax.diploma_project.model.exception.ApplicationException;
import com.github.myrrhax.diploma_project.script.AbstractFullSqlScriptFabric;
import com.github.myrrhax.diploma_project.util.MetadataTypeUtils;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;

@Component("postgresFullFabric")
public class PostgresFullScriptFabric extends AbstractFullSqlScriptFabric {
    Map<ColumnMetadata.ColumnType, String> postgresMapping = new HashMap<>() {{
        put(ColumnMetadata.ColumnType.BOOLEAN, "boolean");
        put(ColumnMetadata.ColumnType.SMALLINT, "smallint");
        put(ColumnMetadata.ColumnType.INT, "integer");
        put(ColumnMetadata.ColumnType.BIGINT, "bigint");
        put(ColumnMetadata.ColumnType.NUMERIC, "numeric");
        put(ColumnMetadata.ColumnType.DECIMAL, "decimal");
        put(ColumnMetadata.ColumnType.FLOAT, "real");
        put(ColumnMetadata.ColumnType.DOUBLE, "double precision");
        put(ColumnMetadata.ColumnType.CHAR, "char");
        put(ColumnMetadata.ColumnType.VARCHAR, "varchar");
        put(ColumnMetadata.ColumnType.TEXT, "text");
        put(ColumnMetadata.ColumnType.UUID, "uuid");
        put(ColumnMetadata.ColumnType.TIME, "time");
        put(ColumnMetadata.ColumnType.DATE, "date");
        put(ColumnMetadata.ColumnType.DATETIME, "timestamp");
        put(ColumnMetadata.ColumnType.TIMESTAMP, "timestamp");
        put(ColumnMetadata.ColumnType.JSON, "jsonb");
    }};

    Map<IndexMetadata.IndexType, String> indexMapping = Map.of(
        IndexMetadata.IndexType.B_TREE, "btree",
        IndexMetadata.IndexType.HASH, "hash"
    );

    @Override
    public void appendPrimaryKeyDefinition(StringBuilder sqlBuilder, TableMetadata table) {
        sqlBuilder.append("\tPRIMARY KEY (");

        List<UUID> primaryKeyParts = new ArrayList<>(table.getPrimaryKeyParts());
        for (int i = 0; i < primaryKeyParts.size(); i++) {
            ColumnMetadata column = table.getColumn(primaryKeyParts.get(i)).orElseThrow();
            sqlBuilder.append(column.getName());
            if (i < primaryKeyParts.size() - 1) {
                sqlBuilder.append(", ");
            }
        }
        sqlBuilder.append(")\n");
    }

    @Override
    public String getMinMaxDefinition(ColumnMetadata column) {
        boolean hasMin = column.getMin() != null;
        boolean hasMax = column.getMax() != null;

        if (!hasMin && !hasMax) {
            throw new ApplicationException("Failed to generate min/max definition");
        }
        boolean hasBetween = hasMin && hasMax;
        StringBuilder result = new StringBuilder();
        result.append(" CHECK(");
        result.append(column.getName());

        if (hasBetween) {
            result.append(" BETWEEN ");
            result.append(column.getMin());
            result.append(" AND ").append(column.getMax());
        } else if (hasMin) {
            result.append(" >= ").append(column.getMin());
        } else {
            result.append(" <= ").append(column.getMax());
        }

        result.append(")");
        return result.toString();
    }

    private String getSuitableType(ColumnMetadata metadata) {
        ColumnMetadata.ColumnType type = metadata.getColumnType();
        if (!Objects.requireNonNullElse(metadata.getAutoIncrement(), false)
            && !(MetadataTypeUtils.lengthLimitedTypes.contains(type) && metadata.getLength() != null)) {
            return postgresMapping.get(type);
        }

        if (MetadataTypeUtils.lengthLimitedTypes.contains(type) ) {
            if (type != ColumnMetadata.ColumnType.DECIMAL) {
                return generateLengthLimitedDefinition(metadata);
            }
            return generateDecimalDefinition(metadata);
        }

        return switch (type) {
            case SMALLINT -> "smallserial";
            case INT -> "serial";
            case BIGINT -> "bigserial";
            default -> throw new RuntimeException("Unsupported autoincrement type: " + type);
        };
    }

    @Override
    public Map<ColumnMetadata.ColumnType, String> getDefinitions() {
        return postgresMapping;
    }

    @Override
    public void appendHeader(StringBuilder sqlBuilder, SchemaStateMetadata schema, String name) {
        sqlBuilder.append("/*\n\tGenerated by ErmDev. Version tag: ")
                .append(name)
                .append("\n*/\n");
    }

    @Override
    public void appendColumnDefinition(StringBuilder sqlBuilder, ColumnMetadata column) {
        String typeName = getSuitableType(column);
        sqlBuilder.append('\t')
                .append(column.getName())
                .append(" ")
                .append(typeName);
        List<ColumnMetadata.ConstraintType> constraints = column.getConstraints();

        for (ColumnMetadata.ConstraintType constraint : constraints) {
            sqlBuilder.append(" ").append(getConstraintName(constraint));
        }

        if (column.getDefaultValue() != null) {
            sqlBuilder.append(" DEFAULT ").append(column.getDefaultValue());
        }

        if (column.getMin() != null || column.getMax() != null) {
            sqlBuilder.append(getMinMaxDefinition(column));
        }
        sqlBuilder.append(',');
    }

    @Override
    public void appendIndexDefinition(StringBuilder indexBuilder, IndexMetadata index) {
        TableMetadata tableMetadata = index.getTable();
        String[] affectedCols = index.getColumnIds().stream()
                .map(col -> tableMetadata.getColumns().get(col))
                .map(ColumnMetadata::getName)
                .toArray(String[]::new);

        indexBuilder.append("CREATE ");
        if (index.isUnique()) {
            indexBuilder.append("UNIQUE ");
        }
        indexBuilder.append("INDEX ");
        if (index.getIndexName() == null) {
            index.computeAndSetName();
        }
        indexBuilder.append(index.getIndexName());
        indexBuilder.append(" ON ");
        indexBuilder.append(tableMetadata.getName());
        indexBuilder.append(" USING ");
        indexBuilder.append(indexMapping.get(index.getIndexType()));
        indexBuilder.append(" (");
        indexBuilder.append(String.join(", ", affectedCols));
        indexBuilder.append(");");
    }
}
