package com.github.myrrhax.diploma_project.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.github.myrrhax.diploma_project.model.enums.MetadataType;
import com.github.myrrhax.diploma_project.model.exception.ApplicationException;
import com.github.myrrhax.diploma_project.util.MetadataTypeUtils;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class IndexMetadata implements AbstractMetadata<UUID> {
    @Builder.Default
    private UUID id = UUID.randomUUID();
    private UUID tableId;
    @Builder.Default
    private List<UUID> columnIds = new ArrayList<>();
    @Builder.Default
    private IndexType indexType = IndexType.B_TREE;
    @JsonProperty("indexName")
    private String name;
    private boolean unique;
    @Builder.Default
    private boolean nameAutogenerated = true;

    @JsonIgnore
    private SchemaStateMetadata schemaState;
    @JsonIgnore
    private TableMetadata table;

    public void computeAndSetName() {
        if (!nameAutogenerated) {
            return;
        }
        String[] affectedColumns = columnIds.stream()
                .map(col -> table.getColumn(col).orElseThrow(() ->
                        new ApplicationException("error.column.notfound")).getName())
                .toArray(String[]::new);
        StringBuilder sb = new StringBuilder();
        if (unique) {
            sb.append("uq_");
        }
        sb.append("idx_");
        sb.append(table.getName());
        sb.append('_');
        sb.append(String.join("_", affectedColumns));

        String generatedName = sb.toString();
        if (table.containsIndex(generatedName)) {
            generatedName += Instant.now().toEpochMilli();
        }

        this.name = generatedName;
    }

    @Override
    public MetadataType getMetadataType() {
        return MetadataType.INDEX;
    }

    @Override
    public boolean contentEquals(AbstractMetadata<UUID> that) {
        if (that instanceof IndexMetadata otherIdx) {
            return MetadataTypeUtils.isFullEquals(columnIds, otherIdx.columnIds)
                    && unique == otherIdx.unique
                    && indexType == otherIdx.indexType;
        }

        return false;
    }

    public enum IndexType {
        B_TREE,
        HASH,
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        IndexMetadata other = (IndexMetadata) o;

        return MetadataTypeUtils.isFullEquals(columnIds, other.columnIds);
    }

    @Override
    public int hashCode() {
        return Objects.hash(columnIds, indexType, name, unique);
    }
}
