package com.github.myrrhax.diploma_project.script.impl.liquibase;

import com.github.myrrhax.diploma_project.model.ColumnMetadata;
import com.github.myrrhax.diploma_project.model.IndexMetadata;
import com.github.myrrhax.diploma_project.model.ReferenceMetadata;
import com.github.myrrhax.diploma_project.model.TableMetadata;
import com.github.myrrhax.diploma_project.model.exception.ApplicationException;
import com.github.myrrhax.diploma_project.script.ScriptFabric;
import com.github.myrrhax.diploma_project.util.MetadataTypeUtils;
import org.springframework.stereotype.Component;

import java.util.EnumMap;
import java.util.Map;
import java.util.Objects;

@Component("liquibaseFullFabric")
public class LiquibaseYamlScriptFabric extends ScriptFabric {
    private static final int CHANGELOG_PADDING_LEVEL = 0;
    public static final int CHANGESET_PADDING_LEVEL = 1;
    public static final int HEADER_PADDING_LEVEL = 2;
    private static final int TABLE_DEFINITION_PADDING_LEVEL = 3;
    private static final int REFERENCE_DEFINITION_PADDING_LEVEL = 3;
    private static final int INDEX_DEFINITION_PADDING_LEVEL = 3;
    private static final int INDEX_ELEMENT_PADDING_LEVEL = 4;
    private static final int TABLE_ELEMENT_PADDING_LEVEL = 4;
    private static final int REFERENCE_ELEMENT_PADDING_LEVEL = 4;
    private static final int COLUMN_DEFINITION_PADDING_LEVEL = 5;
    private static final int INDEX_COLUMN_PADDING_LEVEL = 5;
    private static final int COLUMN_ELEMENT_PADDING_LEVEL = 6;
    private static final int COLUMN_CONSTRAINT_LEVEL = 7;
    private static final String DEFAULT_PADDING = "  ";

    private static final Map<ColumnMetadata.ColumnType, String> defaultTimeValuesMap = Map.of(
            ColumnMetadata.ColumnType.DATE, "CURRENT_DATE",
            ColumnMetadata.ColumnType.TIME, "CURRENT_TIME",
            ColumnMetadata.ColumnType.DATETIME, "CURRENT_TIMESTAMP",
            ColumnMetadata.ColumnType.TIMESTAMP, "CURRENT_TIMESTAMP"
    );
    private static final Map<ColumnMetadata.ColumnType, String> LIQUIBASE_TYPES;

    static {
        LIQUIBASE_TYPES = new EnumMap<>(ColumnMetadata.ColumnType.class);

        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.SMALLINT, "SMALLINT");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.INT, "INT");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.BIGINT, "BIGINT");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.NUMERIC, "NUMERIC");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.CHAR, "CHAR");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.VARCHAR, "VARCHAR");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.TEXT, "TEXT");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.UUID, "UUID");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.FLOAT, "FLOAT");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.DOUBLE, "DOUBLE");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.DECIMAL, "DECIMAL");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.TIME, "TIME");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.DATETIME, "DATETIME");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.TIMESTAMP, "TIMESTAMP");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.JSON, "JSON");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.BOOLEAN, "BOOLEAN");
        LIQUIBASE_TYPES.put(ColumnMetadata.ColumnType.DATE, "DATE");
    }


    @Override
    public void appendHeader(StringBuilder scriptBuilder, String name) {
        appendLine(scriptBuilder, "databaseChangeLog:", CHANGELOG_PADDING_LEVEL);
        appendLine(scriptBuilder, "- changeSet:", CHANGESET_PADDING_LEVEL);
        appendLine(scriptBuilder, "id: ", name, HEADER_PADDING_LEVEL);
        appendLine(scriptBuilder, "author: Generated by ERMDev", HEADER_PADDING_LEVEL);
        appendLine(scriptBuilder, "changes:", HEADER_PADDING_LEVEL);
    }

    @Override
    public void appendTableDefinition(StringBuilder scriptBuilder, TableMetadata table) {
        appendLine(scriptBuilder, "- createTable:", TABLE_DEFINITION_PADDING_LEVEL);
        appendLine(scriptBuilder, "tableName: ", table.getName(), TABLE_ELEMENT_PADDING_LEVEL);
        appendLine(scriptBuilder, "columns:", TABLE_ELEMENT_PADDING_LEVEL);
    }

    @Override
    public void appendColumnDefinition(StringBuilder scriptBuilder, ColumnMetadata column) {
        appendLine(scriptBuilder, "- column:", COLUMN_DEFINITION_PADDING_LEVEL);
        appendLine(scriptBuilder, "name: ", column.getName(), COLUMN_ELEMENT_PADDING_LEVEL);
        String type = column.getColumnType().name();
        if (MetadataTypeUtils.lengthLimitedTypes.contains(column.getColumnType())
                && column.getLength() != null) {
            type = getLengthLimitedType(column);
        } else if (column.getColumnType() == ColumnMetadata.ColumnType.DECIMAL) {
            type = getDecimalDefinition(column);
        }
        appendLine(scriptBuilder, "type: ", type, COLUMN_ELEMENT_PADDING_LEVEL);

        if (column.getDefaultValue() != null) {
            String defaultValue = column.getDefaultValue();
            if (MetadataTypeUtils.timeTypes.contains(column.getColumnType())) {
                defaultValue = defaultTimeValuesMap.get(column.getColumnType());
            }
            appendLine(scriptBuilder, "defaultValue: ", defaultValue, COLUMN_ELEMENT_PADDING_LEVEL);
        }

        if (MetadataTypeUtils.isValidAutoincrement(column)
                && Objects.equals(column.getAutoIncrement(), Boolean.TRUE)) {
            appendLine(scriptBuilder, "autoIncrement: ", "true", COLUMN_ELEMENT_PADDING_LEVEL);
        }

        if (column.isPkPart()
                || column.getMin() != null
                || column.getMax() != null
                || !column.getConstraints().isEmpty()) {
            appendLine(scriptBuilder, "constraints:", COLUMN_ELEMENT_PADDING_LEVEL);
            if (column.isPkPart()) {
                appendLine(scriptBuilder, "primaryKey: ", "true", COLUMN_CONSTRAINT_LEVEL);
            }
            if (!column.getConstraints().isEmpty()) {
                addConstraintsDefinition(column, scriptBuilder);
            }
            if (column.getMin() != null || column.getMax() != null) {
                addMinMaxDefinition(column, scriptBuilder);
            }
        }
    }

    @Override
    public void appendIndexDefinition(StringBuilder indexBuilder, IndexMetadata index) {
        appendLine(indexBuilder, "- createIndex:", INDEX_DEFINITION_PADDING_LEVEL);
        if (index.getName() == null) {
            index.computeAndSetName();
        }

        TableMetadata table = index.getTable();
        String[] columnNames = index.getColumnIds().stream()
                .map(col -> table.getColumn(col).orElseThrow(
                        () -> new ApplicationException("error.column.notfound")
                ).getName())
                .toArray(String[]::new);

        appendLine(indexBuilder, "indexName: ", index.getName(), INDEX_ELEMENT_PADDING_LEVEL);
        appendLine(indexBuilder, "tableName: ", table.getName(), INDEX_ELEMENT_PADDING_LEVEL);
        appendLine(indexBuilder, "columns:", INDEX_ELEMENT_PADDING_LEVEL);

        for (String colName: columnNames) {
            appendLine(indexBuilder, "- column:", INDEX_COLUMN_PADDING_LEVEL);
            appendLine(indexBuilder, "name: ", colName, INDEX_COLUMN_PADDING_LEVEL + 1);
        }
    }

    @Override
    protected void appendEndTablePart(StringBuilder scriptBuilder) {
        scriptBuilder.append('\n');
    }

    @Override
    public void appendReferenceDefinition(StringBuilder scriptBuilder,
                                          String refName,
                                          TableMetadata baseTable,
                                          TableMetadata referencedTable,
                                          String[] baseColumnNames,
                                          String[] referencedColumnNames,
                                          ReferenceMetadata.OnDeleteAction onDeleteAction,
                                          ReferenceMetadata.OnUpdateAction onUpdateAction) {

        appendLine(scriptBuilder, "- addForeignKeyConstraint:", REFERENCE_DEFINITION_PADDING_LEVEL);
        appendLine(scriptBuilder, "constraintName: ", refName, REFERENCE_ELEMENT_PADDING_LEVEL);
        appendLine(scriptBuilder, "baseTableName: ", baseTable.getName(), REFERENCE_ELEMENT_PADDING_LEVEL);
        appendLine(scriptBuilder, "baseColumnNames: ", String.join(", ", baseColumnNames), REFERENCE_ELEMENT_PADDING_LEVEL);
        appendLine(scriptBuilder, "referencedTableName: ", referencedTable.getName(), REFERENCE_ELEMENT_PADDING_LEVEL);
        appendLine(scriptBuilder, "referencedColumnNames: ", String.join(", ", referencedColumnNames), REFERENCE_ELEMENT_PADDING_LEVEL);
        if (onDeleteAction != null) {
            appendLine(scriptBuilder, "onDelete: ", parseAction(onDeleteAction), REFERENCE_ELEMENT_PADDING_LEVEL);
        }
        if (onUpdateAction != null) {
            appendLine(scriptBuilder, "onUpdate: ", parseAction(onUpdateAction), REFERENCE_ELEMENT_PADDING_LEVEL);
        }
    }

    @Override
    public Map<ColumnMetadata.ColumnType, String> getDefinitions() {
        return LIQUIBASE_TYPES;
    }

    @Override
    public String getDecimalDefinition(ColumnMetadata column) {
        return "DECIMAL(" + column.getPrecision() + "," + column.getScale() + ")";
    }

    @Override
    public void appendDropTable(StringBuilder scriptBuilder, TableMetadata fromTable) {
        appendLine(scriptBuilder, "- sql:", TABLE_DEFINITION_PADDING_LEVEL);
        appendLine(scriptBuilder, "sql: ", "DROP TABLE IF EXISTS " + fromTable.getName(), TABLE_ELEMENT_PADDING_LEVEL);
    }

    @Override
    public void appendRenameTable(StringBuilder scriptBuilder, TableMetadata from, TableMetadata to) {
        appendLine(scriptBuilder, "- renameTable", TABLE_DEFINITION_PADDING_LEVEL);
        appendLine(scriptBuilder, "oldTableName: ", from.getName(), TABLE_ELEMENT_PADDING_LEVEL);
        appendLine(scriptBuilder, "newTableName: ", to.getName(), TABLE_ELEMENT_PADDING_LEVEL);
    }

    private String getPadding(int level) {
        return DEFAULT_PADDING.repeat(Math.max(0, level));
    }

    private void appendLine(StringBuilder scriptBuilder, String text, int level) {
        scriptBuilder.append(getPadding(level)).append(text).append("\n");
    }

    private void writeValue(StringBuilder builder, String data) {
        builder.append("\"").append(data).append("\"");
    }

    private void appendLine(StringBuilder scriptBuilder, String key, String value, int level) {
        scriptBuilder.append(getPadding(level)).append(key);
        writeValue(scriptBuilder, value);
        scriptBuilder.append("\n");
    }

    private void addConstraintsDefinition(ColumnMetadata column, StringBuilder scriptBuilder) {
        if (column.getConstraints().contains(ColumnMetadata.ConstraintType.NOT_NULL)) {
            appendLine(scriptBuilder, "nullable: ", "false", COLUMN_CONSTRAINT_LEVEL);
        }
        if (column.getConstraints().contains(ColumnMetadata.ConstraintType.UNIQUE)) {
            appendLine(scriptBuilder, "unique: ", "true", COLUMN_CONSTRAINT_LEVEL);
        }
    }

    private void addMinMaxDefinition(ColumnMetadata column, StringBuilder scriptBuilder) {
        StringBuilder valueBuilder = new StringBuilder();
        boolean isBetween = column.getMin() != null && column.getMax() != null;
        if (column.getMin() != null) {
            valueBuilder.append(column.getName()).append(">=").append(column.getMin());
        }
        if (isBetween) {
            valueBuilder.append(" AND ");
        }
        if (column.getMax() != null) {
            valueBuilder.append(column.getName()).append("<=").append(column.getMax());
        }

        appendLine(scriptBuilder, "checkConstraint: ", valueBuilder.toString(), COLUMN_CONSTRAINT_LEVEL);
    }

}
