package com.github.myrrhax.diploma_project.command.reference;

import com.github.myrrhax.diploma_project.command.MetadataCommand;
import com.github.myrrhax.diploma_project.command.SchemaDifference;
import com.github.myrrhax.diploma_project.model.ReferenceMetadata;
import com.github.myrrhax.diploma_project.model.SchemaStateMetadata;
import com.github.myrrhax.diploma_project.model.enums.ErrorMessageKey;
import com.github.myrrhax.diploma_project.model.exception.ApplicationException;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;

import java.util.Optional;

@Slf4j
@Getter
@Setter
public class RenameReferenceCommand extends MetadataCommand {
    private ReferenceMetadata.ReferenceKey key;
    @NotBlank(message = "{error.validation.null-value}")
    @Size(min = 3, max = 30, message = "{error.validation.name-size}")
    private String newName;

    @Override
    public SchemaDifference execute(SchemaStateMetadata metadata) {
        log.info("Executing Rename Reference Command for schema: {}", metadata.getSchemaId());
        ReferenceMetadata ref = metadata.getReference(this.key)
                .orElseThrow(() -> new ApplicationException(ErrorMessageKey.REFERENCE_NOT_FOUND.getKey()));

        if (metadata.hasReference(newName)) {
            throw new ApplicationException(ErrorMessageKey.REFERENCE_DUPLICATE_NAME.name());
        }
        ref.setName(newName);
        ref.setNameAutogenerated(true);

        SchemaDifference diff = new SchemaDifference();
        diff.upsertReference(ref);

        return diff;
    }
}
