name: build and deploy
on: push

env:
  TARGET_DIR: /home/myrrhax/diploma/diploma-project

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Grant permissions to gradle
        run: chmod +x ./gradlew

      - name: Build without tests
        run: ./gradlew clean build -x test

  deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Prepare directory
        run: |
          if [ -d "${{ env.TARGET_DIR }}" ]; then
            cd ${{ env.TARGET_DIR }}
            sudo docker compose down || true
          fi
          sudo rm -rf ${{ env.TARGET_DIR }}
          sudo chown -R $USER:$USER ${{ env.TARGET_DIR }}

      - name: Copy files
        run: cp -r ./* ${{ env.TARGET_DIR }}/

      - name: Prepare Env
        run: |
          touch ${{ env.TARGET_DIR }}/docker/.env
          cp ${{ secrets.ENV_FILE }} ${{ env.TARGET_DIR }}/docker/

      - name: Start project
        run: |
          cd ${{ env.TARGET_DIR }}
          sudo docker compose up --build -d

      - name: Validate
        run: |
          cd ${{ env.TARGET_DIR }}
          sleep 15
          if [ "$(sudo docker compose ps --format json | grep -c "Exited")" -ne 0 ]; then
            echo "Ошибка: один из контейнеров упал!"
            sudo docker compose logs
            exit 1
          fi
          echo "Деплой успешно завершен и проверен"